# Generated by Django 3.2.5 on 2021-07-22 03:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buffer',
            fields=[
                ('geo', django.contrib.gis.db.models.fields.GeometryField(primary_key=True, serialize=False, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('length', models.FloatField()),
                ('load_valume', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('national_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('total_toll_paid', models.IntegerField()),
                ('last_time_toll_update', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('width', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(primary_key=True, serialize=False, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('toll_per_cross', models.IntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('road_geo', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Nod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('date', models.DateTimeField(null=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_solution.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='national_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_solution.person'),
        ),
    ]
